name: Test

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Volta
      uses: volta-cli/action@v1
    - name: Install dependencies
      run: yarn install
    - name: Lint
      run: yarn lint
